import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Public_Sans, Karla } from "next/font/google"
import { ThemeProvider } from "@/components/providers/theme-provider";

export const fontPublicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
})

export const fontKarla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontPublicSans.variable} ${fontKarla.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
