import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Public_Sans, Karla } from "next/font/google"
import { ThemeProvider } from "@/components/providers/theme-provider";
import { NextIntlClientProvider } from 'next-intl';
import { cookies } from "next/headers"

export const fontPublicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
})

export const fontKarla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const locale = cookieStore.get("NEXT_LOCALE")?.value ?? "en"
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        data-locale={locale}
        className={`${fontPublicSans.variable} ${fontKarla.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider>
            {children}
          </NextIntlClientProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
